### ISSUE TITLE
pre-train checkpoints

### ISSUE THREAD

**Issue by kily-wmz** [ivcylc/qa-mdt#1]
hi！
I am very interested in your work, and I would like to reproduce the code. However, I haven't seen any pre-trained checkpoints. Do I need to train the model myself?

**Comment by ivcylc** [comment]
I will provide it before 9.20 (together on huggingface)

**Comment by ivcylc** [comment]
链接: https://pan.baidu.com/s/1pkLnQhbNeFjKRadXUy_7Iw?pwd=v9dd 提取码: v9dd 
--来自百度网盘超级会员v8的分享 You can provisionally try it out here。 If there is any error, please contact me

**Comment by kily-wmz** [comment]
thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月16日(星期一) 下午4:15
收件人: ***@***.***&gt;; 
抄送: "Kily ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ivcylc/qa-mdt] pre-train checkpoints (Issue #1)














 
链接: https://pan.baidu.com/s/1pkLnQhbNeFjKRadXUy_7Iw?pwd=v9dd 提取码: v9dd
 --来自百度网盘超级会员v8的分享 You can provisionally try it out here。 If there is any error, please contact me

**Comment by kily-wmz** [comment]
hi！
When reproducing the code, I found that the dimensions of the VAE checkpoints and the corresponding model architecture do not match. Could you please share your VAE checkpoints? I would greatly appreciate it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ivcylc/qa-mdt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月16日(星期一) 下午4:15
***@***.***&gt;;
抄送:&nbsp;"Kily ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ivcylc/qa-mdt] pre-train checkpoints (Issue #1)






链接: https://pan.baidu.com/s/1pkLnQhbNeFjKRadXUy_7Iw?pwd=v9dd 提取码: v9dd
--来自百度网盘超级会员v8的分享 You can provisionally try it out here。 If there is any error, please contact me

**Comment by QA-MDT** [comment]
I use the vae from AudioLDM2, can you show me the error?

**Comment by QA-MDT** [comment]
You can add my Wechat : 19524292801

**Comment by ivcylc** [comment]
Check Updated Readme.md and download all checkpoints from links on it
