### ISSUE TITLE
Question about Quality Extractor

### ISSUE THREAD

**Issue by 980202006** [ivcylc/qa-mdt#14]
Hello, this open source is very valuable. I want to train based on my own data, and would like to ask about the details of p-mos. Can you open source the model weights of quality extractor?

**Comment by ivcylc** [comment]
Hi, the music-mos (i.e. quality extractor) is in this [repo](https://github.com/alessandroragano/music-archive-quality-prediction), illustrated in this paper: [ICASSP 2023](https://ieeexplore.ieee.org/document/10096274)

**Comment by 980202006** [comment]
@ivcylc Thank you for your reply.This repo has 4 ckpts. Which ckpt did you use?

**Comment by ivcylc** [comment]
Maybe you can begin your setup [here](https://huggingface.co/jadechoghari/openmusic)
It will autoly help you download the required checkpoint.

**Comment by ivcylc** [comment]
https://huggingface.co/datasets/lichang0928/tmp/tree/main
zip of mp4 is here
this is a video i recorded for helping the training and finetuning pipeline

**Comment by 980202006** [comment]
Thank you!
