### ISSUE TITLE
package  import error

### ISSUE THREAD

**Issue by diggle001** [ivcylc/qa-mdt#15]
Traceback (most recent call last):
  File "/workspace/qa-mdt/gradio/gradio_app.py", line 19, in <module>
    from qa_mdt.pipeline import MOSDiffusionPipeline
ModuleNotFoundError: No module named 'qa_mdt'

**Comment by ivcylc** [comment]
You need to manually change the folder name from "openmusic" to "qa_mdt" as illustrated in the readme.md on huggingface page

**Comment by diggle001** [comment]
thks
