### ISSUE TITLE
抱歉，打扰下，音乐长度可以控制吗？

### ISSUE THREAD

**Issue by SevenMpp** [ivcylc/qa-mdt#17]
我生成了几次，都是10s,请问这个音乐的长度是可以控制的吗，通过描述或其他的办法. 我通过描述与修改配置文件qa_mdt.yaml,将duration 调成20.24,但是未起到作用.

![image](https://github.com/user-attachments/assets/1e9ad1df-adc0-4e1d-8b88-c658d2939d55)

**Comment by ivcylc** [comment]
当然不可以，这个训练的时候就锁定了。
在现在这个版本的模型里，只能重新训练，不然只能生成10秒钟

如果从科研角度的话，今年我看 ICLR 上有些 submitted 的文章可以免训练就解决这个问题， 通过位置编码差值的方法好像，或者也可以用类似 multidiffusion 的方式做inpainting

**Comment by ivcylc** [comment]
奥，Unet based的模型是可以无限延长的，这个只要改变这个数值就可以了，但是我放出来的checkpoint基于DiT类家族的，他的cross attention在channel维度和时间-频率维度上都有计算，所以网络结构变相限制了这个能力。

不过DiT类架构的延展性，科研角度肯定是可以实现的，NLP很多年前就在外推上处理这些功能

**Comment by SevenMpp** [comment]
好的 非常感谢您的回答，那我试试将您现在这里的DiT 换成 Unet based。

**Comment by ivcylc** [comment]
我论文里有训练的Unet-based的结果，你可以给一个邮箱，我发你一下ckpt

**Comment by SevenMpp** [comment]
> 我论文里有训练的Unet-based的结果，你可以给一个邮箱，我发你一下ckpt

好的 非常感谢 您发给QQ 邮箱里吧 646662096@qq.com,然后我也弄点数据训练以下，可以指定使用Unet 还是DIT吗？

**Comment by ivcylc** [comment]
好的，可能您要等一段时间。

可以的，我在 readme.md 中写得很详细，请参考[这一段](https://github.com/ivcylc/qa-mdt?tab=readme-ov-file#how-to-prepare-for-training-or-fine-tuning)

**Comment by SevenMpp** [comment]
好的 已经非常感谢啦！！！
