### ISSUE TITLE
not able to run the code getting AttributeError: module diffusers has no attribute QAMDTModel

### ISSUE THREAD

**Issue by Vaibhav99mishra** [ivcylc/qa-mdt#18]
Repository structure:
/root/.cache/huggingface/hub/models--jadechoghari--openmusic/snapshots/6a0a1f2e98b30a14e0e884200213b256d95b41ec
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-afbed416ddf1>](https://localhost:8080/#) in <cell line: 13>()
     11 
     12 # Load the pipeline
---> 13 pipe = DiffusionPipeline.from_pretrained("jadechoghari/openmusic")
     14 
     15 # Generate an image

5 frames
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py](https://localhost:8080/#) in _inner_fn(*args, **kwargs)
    112             kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
    113 
--> 114         return fn(*args, **kwargs)
    115 
    116     return _inner_fn  # type: ignore

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    723                     " is neither a valid local path nor a valid repo id. Please check the parameter."
    724                 )
--> 725             cached_folder = cls.download(
    726                 pretrained_model_name_or_path,
    727                 cache_dir=cache_dir,

[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py](https://localhost:8080/#) in _inner_fn(*args, **kwargs)
    112             kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
    113 
--> 114         return fn(*args, **kwargs)
    115 
    116     return _inner_fn  # type: ignore

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py](https://localhost:8080/#) in download(cls, pretrained_model_name, **kwargs)
   1373 
   1374             # retrieve passed components that should not be downloaded
-> 1375             pipeline_class = _get_pipeline_class(
   1376                 cls,
   1377                 config_dict,

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_loading_utils.py](https://localhost:8080/#) in _get_pipeline_class(class_obj, config, load_connected_pipeline, custom_pipeline, repo_id, hub_revision, class_name, cache_dir, revision)
    368     class_name = class_name[4:] if class_name.startswith("Flax") else class_name
    369 
--> 370     pipeline_cls = getattr(diffusers_module, class_name)
    371 
    372     if load_connected_pipeline:

[/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py](https://localhost:8080/#) in __getattr__(self, name)
    844             value = getattr(module, name)
    845         else:
--> 846             raise AttributeError(f"module {self.__name__} has no attribute {name}")
    847 
    848         setattr(self, name, value)

AttributeError: module diffusers has no attribute QAMDTModel

**Comment by ivcylc** [comment]
sorry for late reply.

[https://huggingface.co/datasets/lichang0928/tmp/tree/main](https://huggingface.co/datasets/lichang0928/tmp/tree/main)
zip of mp4 is here
this is a video i recorded for helping the training and finetuning pipeline

which may be of some help for you to start up~
