### ISSUE TITLE
Add QA-MDT to HF hub (native integration)

### ISSUE THREAD

**Issue by jadechoghari** [ivcylc/qa-mdt#2]
Hello @ivcylc and team,
Congratulations on this amazing work—the model (TTM) looks incredible! 🎉

You should consider adding the model (inference at least) to the Hugging Face Hub 🤗. Doing so could increase the model's visibility and make it easier for everyone to use. It can easily be made compatible **natively** with the Hugging Face Transformers library.

Will do the work - other folks from HF will be available to help.
From your behalf we just need you to provide the checkpoints as said on HF and if any questions arise during the process we can open an issue :)

Soon, it will be easily usable with just one line of code. And will add a gradio demo as well!

Best regards,
Jade

**Comment by ivcylc** [comment]
I'm new to it and keep trying these days, thanks so much for your suggestion

**Comment by jadechoghari** [comment]
@ivcylc no worries, we will do it for you :) 🤗
Is it possible to just upload the model checkpoints, so I can donwload them easily into colab?

**Comment by ivcylc** [comment]
I have mailed you for further help, thanks!!
