### ISSUE TITLE
ModuleNotFoundError: No module named 'qa_mdt'

### ISSUE THREAD

**Issue by fahdmirza** [ivcylc/qa-mdt#9]
I am trying to install this locally on Ubuntu 22.04 but getting error. Are you able to help me please? 

Following are the commands I am following with error:

conda create -n om python=3.11 -y && conda activate om

git clone https://github.com/ivcylc/qa-mdt.git && cd qa-mdt

pip install -r gradio/requirements.txt

python3 gradio/gradio_app.py 

Traceback (most recent call last):
  File "/home/Ubuntu/qa-mdt/gradio/gradio_app.py", line 19, in <module>
    from qa_mdt.pipeline import MOSDiffusionPipeline
ModuleNotFoundError: No module named 'qa_mdt'
(om) Ubuntu@0041-kci-prxmx10171:~/qa-mdt$

**Comment by ivcylc** [comment]
Hi, the gradio_app is made by @jadechoghari 
But i think that, you should add:
`import sys
sys.path.append('/home/Ubuntu')`

**Comment by jadechoghari** [comment]
@fahdmirza Try commenting out this line in `app.py`: `os.system('git clone https://huggingface.co/jadechoghari/openmusic')`. 

Instead, clone it directly inside the gradio folder: `git clone https://huggingface.co/jadechoghari/openmusic`. Also you after it's cloned rename `openmusic` to `qa_mdt` as mentioned in the model card documentation: https://huggingface.co/jadechoghari/openmusic., then run app.py again.

I'll update the Gradio documentation to make it clearer. (It's a naming issue).
